#!/usr/bin/perl

# We took this script from Inkscape.
# http://osdir.com/ml/graphics.inkscape.devel/2004-02/msg00466.html
# OSP, May 2010.

# This is a script to render a plain text file into SVG, line by line.

use strict;
use open ':encoding(utf8)';
binmode(STDOUT, ":utf8");
use SVG;
use Net::Identica;

my $svg = new SVG;

# nach fc-list :)
my $font = "NotCourierSans" unless $ARGV[1];
$font = $ARGV[1] unless not $ARGV[1];
open TEXT, "<$ARGV[0]";

$svg->comment('Generated by txt2svg generated by SVG.pm');

my $nt = Net::Identica->new(
	decode_html_entities => 1,
	username => "palabras",
	password => "simple",
);

my $r = $nt->public_timeline();

my $i=0;
foreach my $dent (@{$r}) {
	my $dent_text = $dent->{text};
	printf "%s\n", $dent_text;
}

