#!/usr/bin/perl

# We took this script from Inkscape.
# http://osdir.com/ml/graphics.inkscape.devel/2004-02/msg00466.html
# OSP, May 2010.

# This is a script to render a plain text file into SVG, line by line.

use strict;
use open ':encoding(utf8)';
binmode(STDOUT, ":utf8");
use SVG;
use vars qw($VERSION);
$VERSION = '1.00';

my $svg = new SVG;

my $font = "NotCourierSans" unless $ARGV[1];
$font = $ARGV[1] unless not $ARGV[1];
open TEXT, "<$ARGV[0]";

$svg->comment('Generated by txt2svg generated by SVG.pm');

my $i=0;
while (<TEXT>) {
    chomp($_);
    s/\t/    /g;        # Convert tabs into spaces, otherwise we get errors about invalid char

    my $text = $svg->text(id    => "text_line_$i",
			  x     => 10,
			  y     => 24*(1+$i),
			  'xml:space' => 'preserve',
			  style => { #'font' => 'Courier', 
#				     'font-family' => 'Courier 10 pitch', 
				     'font-family' => $font,
				     'font-size' => 24,
				 }
			  )
	->cdata($_);
    $i++;
}
close TEXT;

print $svg->xmlify();
